# spring-boot: true
spring:
  application:
    name: tierpeek
  datasource:
    url: jdbc:postgresql://localhost:5432/tierpeek
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  cache:
    type: redis

riot:
  api:
    base-url: https://api.riotgames.com
    key: ${RIOT_API_KEY}
    rate-limit:
      requests-per-second: 20
      requests-per-two-minutes: 100

rank:
  snapshot:
    fixedRateMs: 1800000

match:
  sync:
    fixedRateMs: 1800000

server:
  port: 8080

logging:
  level:
    root: WARN
    com.tierpeek: INFO
    org.hibernate.orm.jdbc: WARN