spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
    com.tierpeek: DEBUG
    org.hibernate.orm.jdbc: WARN
